package com.bootdemo.lmy.demo.mapper;

import com.bootdemo.lmy.demo.model.Question;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated Sun Oct 13 23:18:04 CST 2019
     */
    int addViewCount(Question question);

    void intCommentCount(Question question);
}