package com.bootdemo.lmy.demo.model;

public class CommentWithBLOBs extends Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.gmt_create
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    private String gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.gmt_modified
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    private String gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentator
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    private String commentator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.gmt_create
     *
     * @return the value of t_comment.gmt_create
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.gmt_create
     *
     * @param gmtCreate the value for t_comment.gmt_create
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.gmt_modified
     *
     * @return the value of t_comment.gmt_modified
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    public String getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.gmt_modified
     *
     * @param gmtModified the value for t_comment.gmt_modified
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    public void setGmtModified(String gmtModified) {
        this.gmtModified = gmtModified == null ? null : gmtModified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentator
     *
     * @return the value of t_comment.commentator
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    public String getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentator
     *
     * @param commentator the value for t_comment.commentator
     *
     * @mbg.generated Mon Oct 21 23:09:52 CST 2019
     */
    public void setCommentator(String commentator) {
        this.commentator = commentator == null ? null : commentator.trim();
    }
}